services:
  - type: web
    name: rota-dos-celulares-66
    runtime: node
    plan: free
    buildCommand: cd server && npm install && cd ../admin-app && npm install && npm run build
    startCommand: node server/server.js
    envVars:
      - key: SESSION_COOKIE_NAME
        value: rc66_session
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
